spring:
  application:
    name: task-system
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:${URL_DATABASE}://${URL_HOST}:${URL_PORT}/${URL_DATABASE_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
app:
  security:
    expirationAccessToken: 900000
    expirationRefreshToken: 86400000
